language: r

cache: packages

warnings_are_errors: false

addons:
    apt:
        packages:
            - sshpass
            
after_success:
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "deploy" && mkdir build
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "deploy" && mv * build
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "deploy" && tar -czf package.tgz build
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "deploy" && export SSHPASS=$DEPLOY_PASS 
    - test $TRAVIS_PULL_REQUEST == "false" && test $TRAVIS_BRANCH == "deploy" && sshpass -e scp -o StrictHostKeyChecking=no package.tgz $DEPLOY_USER@$DEPLOY_HOST:$DEPLOY_PATH
    